// Authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


// Modes
export const TOGGLE_MODES = 'TOGGLE_MODES'


//Question
export const DISPLAY_QUESTION_DETAILS = 'DISPLAY_QUESTION_DETAILS'

// Answer
export const DISPLAY_ANSWER_DETAILS = 'DISPLAY_ANSWER_DETAILS'
export const DISPLAY_ANSWER_QUESTION_DATA = 'DISPLAY_ANSWER_QUESTION_DATA'
export const GET_ANSWER_ID = 'GET_ANSWER_ID'


// Comment
export const DISPLAY_COMMENT_DETAILS = 'DISPLAY_COMMENT_DETAILS'

// Profile
export const DISPLAY_PROFILE_DETAILS = 'DISPLAY_PROFILE_DETAILS'
export const GET_USER_ID = 'GET_USER_ID'
export const REQUEST_USER_DETAIL = 'REQUEST_USER_DETAIL,'

//Like
export const INCREMENT_LIKE_QUESTION = 'INCREMENT_LIKE_QUESTION'





